create table category
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table booking
(
    id      int8 generated by default as identity,
    created timestamp,
    status  varchar(255),
    sum     float8 not null,
    updated timestamp,
    user_id int8,
    primary key (id)
);
create table order_product_list
(
    order_id        int8 not null,
    product_list_id int8 not null
);
create table product
(
    id           int8 generated by default as identity,
    name         varchar(255),
    color        varchar(255),
    details      varchar(255),
    manufacturer varchar(255),
    price        float8,
    size         varchar(255),
    primary key (id)
);
create table product_category
(
    product_id  int8 not null,
    category_id int8 not null
);
create table client
(
    id         int8 generated by default as identity,
    email      varchar(255),
    first_name varchar(255),
    last_name  varchar(255),
    phone      varchar(255),
    primary key (id)
);
alter table if exists order_product_list
    add constraint UK_i69ycibqg94pqb8wmvst5qpeu unique (product_list_id);
alter table if exists booking
    add constraint FKt7abetueht6dd1gs9jyl3o4t7 foreign key (user_id) references client;
alter table if exists order_product_list
    add constraint FKqnqy39b3wm1r0hf75dtipvr1d foreign key (product_list_id) references product;
alter table if exists order_product_list
    add constraint FKcx9ixcmopspmnj8nnqmry1eiq foreign key (order_id) references booking;
alter table if exists product_category
    add constraint category_id foreign key (category_id) references category;
alter table if exists product_category
    add constraint product_id foreign key (product_id) references product