create table buckets
(
    id int8 generated by default as identity,
    primary key (id)
);
create table buckets_product
(
    bucket_id  int8 not null,
    product_id int8 not null
);
create table categories
(
    id   int8 generated by default as identity,
    name varchar(255),
    primary key (id)
);
create table orders
(
    id      int8 generated by default as identity,
    created timestamp,
    status  varchar(255),
    sum     float8 not null,
    updated timestamp,
    primary key (id)
);
create table orders_details
(
    id         int8 generated by default as identity,
    amount     float8 not null,
    price      float8 not null,
    order_id   int8,
    product_id int8,
    details_id int8   not null,
    primary key (id)
);
create table products
(
    id           int8 generated by default as identity,
    name         varchar(255),
    color        varchar(255),
    details      varchar(255),
    manufacturer varchar(255),
    price        float8,
    size         varchar(255),
    primary key (id)
);
create table products_categories
(
    product_id  int8 not null,
    category_id int8 not null
);
alter table if exists orders_details
    add constraint UK_kk6y3pyhjt6kajomtjbhsoajo unique (details_id);
alter table if exists buckets_product
    add constraint FKic6ur6tnwvwrxpomniehbv383 foreign key (product_id) references products;
alter table if exists buckets_product
    add constraint FKje1rq0ugm3ggvsstdi47ep6we foreign key (bucket_id) references buckets;
alter table if exists orders_details
    add constraint FK5o977kj2vptwo70fu7w7so9fe foreign key (order_id) references orders;
alter table if exists orders_details
    add constraint FKs0r9x49croribb4j6tah648gt foreign key (product_id) references products;
alter table if exists orders_details
    add constraint FKgvp1k7a3ubdboj3yhnawd5m1p foreign key (details_id) references orders_details;
alter table if exists products_categories
    add constraint FKqt6m2o5dly3luqcm00f5t4h2p foreign key (category_id) references categories;
alter table if exists products_categories
    add constraint FKtj1vdea8qwerbjqie4xldl1el foreign key (product_id) references products